#!/bin/bash
set -xe

cd DevOps_Project_2/Terraform

sed -i "s/server_name/${SERVER_NAME}/g" backend.tf
export TF_VAR_name="${SERVER_NAME}"

terraform init
terraform plan
terraform ${TERRAFORM_ACTION} -auto-approve

if [ "${TERRAFORM_ACTION}" = "destroy" ]; then
    exit 0
fi

cd ../Ansible

echo "Waiting 30 seconds..."
sleep 30

export ANSIBLE_HOST_KEY_CHECKING=False

ansible all \
    -i /opt/ansible/inventory/aws_ec2.yaml \
    -u ec2-user \
    --private-key=/opt/ansible/1st_key.pem \
    -m wait_for_connection \
    -a "timeout=300"

ansible-playbook \
    -i /opt/ansible/inventory/aws_ec2.yaml \
    -u ec2-user \
    --private-key=/opt/ansible/1st_key.pem \
    apache.yaml
