- name: Configure Apache web server
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: yes

  vars:
    apache_ssh_private_key: "/opt/ansible/keys/1st_key.pem"
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install required packages
      package:
        name:
          - httpd
          - php
          - git
          - wget
        state: present

    - name: Deploy the application code from GitHub
      git:
        repo: "https://github.com/SouravDasHriday/ansible-web-demo.git"
        dest: "/var/www/html"
        version: "main"
        force: true

    - name: Download and install terraform
      unarchive:
        src: "https://releases.hashicorp.com/terraform/1.15.7/terraform_1.15.7_linux_arm64.zip"
        dest: "/usr/local/bin/"
        remote_src: yes
        mode: '0755'
    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true
